version: "3.7"

services:

  lab:
    container_name: stanspace
    build:
      context: .
      dockerfile: ./lab-Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
    environment:
      TZ: Europe/London
      JUPYTER_ENABLE_LAB: 'yes'
    volumes:
      - type: bind
        source: ./workbench
        target: /home/jovyan/work
    ports:
      - "0.0.0.0:8888:8888"
    networks:
      - net


networks:
  net:
